2016/04/10 12:28:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "admin".' in Z:\home\yii\www\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('admin')
#1 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 Z:\home\yii\www\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=admin
---
2016/04/10 12:40:03 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[42000] [1049] Unknown database 'testdrive'' in Z:\home\yii\www\framework\db\CDbConnection.php:399
Stack trace:
#0 Z:\home\yii\www\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 Z:\home\yii\www\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 Z:\home\yii\www\framework\base\CModule.php(394): CDbConnection->init()
#3 Z:\home\yii\www\framework\base\CModule.php(103): CModule->getComponent('db')
#4 Z:\home\yii\www\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 Z:\home\yii\www\framework\web\CFormModel.php(39): ModelCode->init()
#6 Z:\home\yii\www\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 Z:\home\yii\www\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 Z:\home\yii\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 Z:\home\yii\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('index')
#13 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 Z:\home\yii\www\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php?r=gii/model/index
HTTP_REFERER=http://www.yii/index.php?r=gii/controller/index
---
2016/04/10 12:40:15 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[42000] [1049] Unknown database 'testdrive'' in Z:\home\yii\www\framework\db\CDbConnection.php:399
Stack trace:
#0 Z:\home\yii\www\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 Z:\home\yii\www\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 Z:\home\yii\www\framework\base\CModule.php(394): CDbConnection->init()
#3 Z:\home\yii\www\framework\base\CModule.php(103): CModule->getComponent('db')
#4 Z:\home\yii\www\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 Z:\home\yii\www\framework\web\CFormModel.php(39): ModelCode->init()
#6 Z:\home\yii\www\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 Z:\home\yii\www\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 Z:\home\yii\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 Z:\home\yii\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('index')
#13 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 Z:\home\yii\www\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php?r=gii/model/index
HTTP_REFERER=http://www.yii/index.php?r=gii
---
2016/04/10 17:27:45 [error] [exception.CException] exception 'CException' with message 'Property "ContController._basePath" is not defined.' in Z:\home\yii\www\framework\base\CComponent.php:130
Stack trace:
#0 Z:\home\yii\www\framework\base\CApplication.php(255): CComponent->__get('_basePath')
#1 Z:\home\yii\www\protected\views\cont\index.php(7): CApplication->getBasePath()
#2 Z:\home\yii\www\framework\web\CBaseController.php(126): require('Z:\home\yii\www...')
#3 Z:\home\yii\www\framework\web\CBaseController.php(95): CBaseController->renderInternal('Z:\home\yii\www...', NULL, true)
#4 Z:\home\yii\www\framework\web\CController.php(869): CBaseController->renderFile('Z:\home\yii\www...', NULL, true)
#5 Z:\home\yii\www\framework\web\CController.php(782): CController->renderPartial('index', NULL, true)
#6 Z:\home\yii\www\protected\controllers\ContController.php(7): CController->render('index')
#7 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): ContController->actionIndex()
#8 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 Z:\home\yii\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 Z:\home\yii\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('')
#12 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('cont')
#13 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#14 Z:\home\yii\www\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/index.php?r=cont
HTTP_REFERER=http://www.yii/index.php?r=gii/controller/index
---
2016/04/10 17:28:20 [error] [exception.CException] exception 'CException' with message 'Property "ContController._basePath" is not defined.' in Z:\home\yii\www\framework\base\CComponent.php:130
Stack trace:
#0 Z:\home\yii\www\framework\base\CApplication.php(255): CComponent->__get('_basePath')
#1 Z:\home\yii\www\protected\views\cont\index.php(7): CApplication->getBasePath()
#2 Z:\home\yii\www\framework\web\CBaseController.php(126): require('Z:\home\yii\www...')
#3 Z:\home\yii\www\framework\web\CBaseController.php(95): CBaseController->renderInternal('Z:\home\yii\www...', NULL, true)
#4 Z:\home\yii\www\framework\web\CController.php(869): CBaseController->renderFile('Z:\home\yii\www...', NULL, true)
#5 Z:\home\yii\www\framework\web\CController.php(782): CController->renderPartial('index', NULL, true)
#6 Z:\home\yii\www\protected\controllers\ContController.php(7): CController->render('index')
#7 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): ContController->actionIndex()
#8 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 Z:\home\yii\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 Z:\home\yii\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('')
#12 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('cont')
#13 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#14 Z:\home\yii\www\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/index.php?r=cont
HTTP_REFERER=http://www.yii/index.php?r=gii/controller/index
---
2016/04/10 17:30:37 [error] [exception.CException] exception 'CException' with message 'Property "ContController._baseUrl" is not defined.' in Z:\home\yii\www\framework\base\CComponent.php:130
Stack trace:
#0 Z:\home\yii\www\framework\web\CHttpRequest.php(398): CComponent->__get('_baseUrl')
#1 Z:\home\yii\www\protected\views\cont\index.php(7): CHttpRequest->getBaseUrl()
#2 Z:\home\yii\www\framework\web\CBaseController.php(126): require('Z:\home\yii\www...')
#3 Z:\home\yii\www\framework\web\CBaseController.php(95): CBaseController->renderInternal('Z:\home\yii\www...', NULL, true)
#4 Z:\home\yii\www\framework\web\CController.php(869): CBaseController->renderFile('Z:\home\yii\www...', NULL, true)
#5 Z:\home\yii\www\framework\web\CController.php(782): CController->renderPartial('index', NULL, true)
#6 Z:\home\yii\www\protected\controllers\ContController.php(7): CController->render('index')
#7 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): ContController->actionIndex()
#8 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 Z:\home\yii\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 Z:\home\yii\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('')
#12 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('cont')
#13 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#14 Z:\home\yii\www\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/index.php?r=cont
HTTP_REFERER=http://www.yii/index.php?r=gii/controller/index
---
2016/04/26 18:08:04 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[42000] [1049] Unknown database 'twl'' in Z:\home\yii\www\framework\db\CDbConnection.php:399
Stack trace:
#0 Z:\home\yii\www\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 Z:\home\yii\www\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 Z:\home\yii\www\framework\base\CModule.php(394): CDbConnection->init()
#3 Z:\home\yii\www\framework\base\CModule.php(103): CModule->getComponent('db')
#4 Z:\home\yii\www\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 Z:\home\yii\www\framework\web\CFormModel.php(39): ModelCode->init()
#6 Z:\home\yii\www\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 Z:\home\yii\www\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 Z:\home\yii\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 Z:\home\yii\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('index')
#13 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 Z:\home\yii\www\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php?r=gii/model/index
HTTP_REFERER=http://www.yii/index.php?r=gii/controller/index
---
2016/04/26 18:18:19 [error] [exception.CException] exception 'CException' with message 'Не определено свойство "Tasks.k".' in Z:\home\yii\www\framework\base\CComponent.php:130
Stack trace:
#0 Z:\home\yii\www\framework\db\ar\CActiveRecord.php(145): CComponent->__get('k')
#1 Z:\home\yii\www\protected\controllers\TasksController.php(11): CActiveRecord->__get('k')
#2 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionIndex()
#3 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 Z:\home\yii\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 Z:\home\yii\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('')
#7 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('tasks')
#8 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#9 Z:\home\yii\www\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/index.php?r=tasks
---
2016/04/26 19:51:30 [error] [system.db.CDbCommand] Не удалось выполнить CDbCommand::fetchAll(): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'yii.task' doesn't exist. Выполнявшийся SQL-запрос: SELECT * FROM task.
in Z:\home\yii\www\protected\controllers\TasksController.php (9)
in Z:\home\yii\www\index.php (13)
2016/04/26 19:51:30 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand не удалось исполнить SQL-запрос: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'yii.task' doesn't exist. The SQL statement executed was: SELECT * FROM task' in Z:\home\yii\www\framework\db\CDbCommand.php:543
Stack trace:
#0 Z:\home\yii\www\framework\db\CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 Z:\home\yii\www\framework\db\ar\CActiveRecord.php(1586): CDbCommand->queryAll()
#2 Z:\home\yii\www\protected\controllers\TasksController.php(9): CActiveRecord->findAllBySql('SELECT * FROM t...')
#3 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionIndex()
#4 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 Z:\home\yii\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#6 Z:\home\yii\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('')
#8 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('tasks')
#9 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 Z:\home\yii\www\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/index.php?r=tasks
---
2016/04/26 19:58:39 [error] [system.db.CDbCommand] Не удалось выполнить CDbCommand::fetchColumn(): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SELECT * FROM comments WHERE num = NULL' at line 1. Выполнявшийся SQL-запрос: SELECT COUNT(*) FROM `comments` `t` WHERE SELECT * FROM comments WHERE num = :num.
in Z:\home\yii\www\protected\controllers\TasksController.php (14)
in Z:\home\yii\www\index.php (13)
2016/04/26 19:58:39 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand не удалось исполнить SQL-запрос: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SELECT * FROM comments WHERE num = NULL' at line 1. The SQL statement executed was: SELECT COUNT(*) FROM `comments` `t` WHERE SELECT * FROM comments WHERE num = :num' in Z:\home\yii\www\framework\db\CDbCommand.php:543
Stack trace:
#0 Z:\home\yii\www\framework\db\CDbCommand.php(433): CDbCommand->queryInternal('fetchColumn', 0, Array)
#1 Z:\home\yii\www\framework\db\ar\CActiveRecord.php(1606): CDbCommand->queryScalar()
#2 Z:\home\yii\www\protected\controllers\TasksController.php(14): CActiveRecord->count('SELECT * FROM c...', Array)
#3 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionIndex()
#4 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 Z:\home\yii\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#6 Z:\home\yii\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('')
#8 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('tasks')
#9 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 Z:\home\yii\www\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/index.php?r=tasks
---
2016/04/26 20:30:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "?num=1".' in Z:\home\yii\www\framework\web\CController.php:483
Stack trace:
#0 Z:\home\yii\www\framework\web\CController.php(270): CController->missingAction('?num=1')
#1 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('?num=1')
#2 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('tasks/?num=1')
#3 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 Z:\home\yii\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php?r=tasks/?num=1
HTTP_REFERER=http://www.yii/index.php?r=tasks/
---
2016/04/26 20:31:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "index?num=1".' in Z:\home\yii\www\framework\web\CController.php:483
Stack trace:
#0 Z:\home\yii\www\framework\web\CController.php(270): CController->missingAction('index?num=1')
#1 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('index?num=1')
#2 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('tasks/index?num...')
#3 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 Z:\home\yii\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php?r=tasks/index?num=1
---
2016/04/26 21:22:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "task?num=1".' in Z:\home\yii\www\framework\web\CController.php:483
Stack trace:
#0 Z:\home\yii\www\framework\web\CController.php(270): CController->missingAction('task?num=1')
#1 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('task?num=1')
#2 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('tasks/task?num=...')
#3 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 Z:\home\yii\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php?r=tasks/task?num=1
HTTP_REFERER=http://www.yii/index.php?r=tasks/index
---
2016/04/26 21:42:24 [error] [exception.CException] exception 'CException' with message 'Не определено свойство "Tasks.username".' in Z:\home\yii\www\framework\base\CComponent.php:130
Stack trace:
#0 Z:\home\yii\www\framework\db\ar\CActiveRecord.php(145): CComponent->__get('username')
#1 Z:\home\yii\www\framework\web\helpers\CHtml.php(2729): CActiveRecord->__get('username')
#2 Z:\home\yii\www\framework\web\helpers\CHtml.php(2452): CHtml::resolveValue(Object(Tasks), 'username')
#3 Z:\home\yii\www\framework\web\helpers\CHtml.php(1534): CHtml::activeInputField('text', Object(Tasks), 'username', Array)
#4 Z:\home\yii\www\protected\views\tasks\index.php(35): CHtml::activeTextField(Object(Tasks), 'username')
#5 Z:\home\yii\www\framework\web\CBaseController.php(126): require('Z:\home\yii\www...')
#6 Z:\home\yii\www\framework\web\CBaseController.php(95): CBaseController->renderInternal('Z:\home\yii\www...', Array, true)
#7 Z:\home\yii\www\framework\web\CController.php(869): CBaseController->renderFile('Z:\home\yii\www...', Array, true)
#8 Z:\home\yii\www\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#9 Z:\home\yii\www\protected\controllers\TasksController.php(18): CController->render('index', Array)
#10 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionIndex()
#11 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#12 Z:\home\yii\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#13 Z:\home\yii\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('')
#15 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('tasks')
#16 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#17 Z:\home\yii\www\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/index.php?r=tasks
HTTP_REFERER=http://www.yii/index.php?r=tasks
---
2016/04/26 21:43:02 [error] [exception.CException] exception 'CException' with message 'Не определено свойство "Tasks.username".' in Z:\home\yii\www\framework\base\CComponent.php:130
Stack trace:
#0 Z:\home\yii\www\framework\db\ar\CActiveRecord.php(145): CComponent->__get('username')
#1 Z:\home\yii\www\framework\web\helpers\CHtml.php(2729): CActiveRecord->__get('username')
#2 Z:\home\yii\www\framework\web\helpers\CHtml.php(2452): CHtml::resolveValue(Object(Tasks), 'username')
#3 Z:\home\yii\www\framework\web\helpers\CHtml.php(1534): CHtml::activeInputField('text', Object(Tasks), 'username', Array)
#4 Z:\home\yii\www\protected\views\tasks\index.php(33): CHtml::activeTextField(Object(Tasks), 'username')
#5 Z:\home\yii\www\framework\web\CBaseController.php(126): require('Z:\home\yii\www...')
#6 Z:\home\yii\www\framework\web\CBaseController.php(95): CBaseController->renderInternal('Z:\home\yii\www...', Array, true)
#7 Z:\home\yii\www\framework\web\CController.php(869): CBaseController->renderFile('Z:\home\yii\www...', Array, true)
#8 Z:\home\yii\www\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#9 Z:\home\yii\www\protected\controllers\TasksController.php(18): CController->render('index', Array)
#10 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionIndex()
#11 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#12 Z:\home\yii\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#13 Z:\home\yii\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('')
#15 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('tasks')
#16 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#17 Z:\home\yii\www\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/index.php?r=tasks
HTTP_REFERER=http://www.yii/index.php?r=tasks
---
2016/04/26 21:43:19 [error] [php] Missing argument 2 for CHtml::label(), called in Z:\home\yii\www\protected\views\tasks\index.php on line 32 and defined (Z:\home\yii\www\framework\web\helpers\CHtml.php:577)
Stack trace:
#0 Z:\home\yii\www\framework\web\CBaseController.php(95): TasksController->renderInternal()
#1 Z:\home\yii\www\framework\web\CController.php(869): TasksController->renderFile()
#2 Z:\home\yii\www\framework\web\CController.php(782): TasksController->renderPartial()
#3 Z:\home\yii\www\protected\controllers\TasksController.php(18): TasksController->render()
#4 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionIndex()
#5 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#6 Z:\home\yii\www\framework\web\CController.php(286): TasksController->runAction()
#7 Z:\home\yii\www\framework\web\CController.php(265): TasksController->runActionWithFilters()
#8 Z:\home\yii\www\framework\web\CWebApplication.php(282): TasksController->run()
#9 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#10 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#11 Z:\home\yii\www\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php?r=tasks
in Z:\home\yii\www\protected\views\tasks\index.php (32)
in Z:\home\yii\www\protected\controllers\TasksController.php (18)
in Z:\home\yii\www\index.php (13)
2016/04/26 21:49:59 [error] [php] Object of class Tasks could not be converted to string (Z:\home\yii\www\protected\views\tasks\index.php:36)
Stack trace:
#0 Z:\home\yii\www\framework\web\CController.php(869): TasksController->renderFile()
#1 Z:\home\yii\www\framework\web\CController.php(782): TasksController->renderPartial()
#2 Z:\home\yii\www\protected\controllers\TasksController.php(18): TasksController->render()
#3 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionIndex()
#4 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 Z:\home\yii\www\framework\web\CController.php(286): TasksController->runAction()
#6 Z:\home\yii\www\framework\web\CController.php(265): TasksController->runActionWithFilters()
#7 Z:\home\yii\www\framework\web\CWebApplication.php(282): TasksController->run()
#8 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 Z:\home\yii\www\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php?r=tasks
in Z:\home\yii\www\protected\views\tasks\index.php (36)
in Z:\home\yii\www\protected\controllers\TasksController.php (18)
in Z:\home\yii\www\index.php (13)
2016/04/26 21:51:21 [error] [php] Object of class Tasks could not be converted to string (Z:\home\yii\www\protected\views\tasks\index.php:36)
Stack trace:
#0 Z:\home\yii\www\framework\web\CController.php(869): TasksController->renderFile()
#1 Z:\home\yii\www\framework\web\CController.php(782): TasksController->renderPartial()
#2 Z:\home\yii\www\protected\controllers\TasksController.php(18): TasksController->render()
#3 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionIndex()
#4 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 Z:\home\yii\www\framework\web\CController.php(286): TasksController->runAction()
#6 Z:\home\yii\www\framework\web\CController.php(265): TasksController->runActionWithFilters()
#7 Z:\home\yii\www\framework\web\CWebApplication.php(282): TasksController->run()
#8 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 Z:\home\yii\www\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php?r=tasks
in Z:\home\yii\www\protected\views\tasks\index.php (36)
in Z:\home\yii\www\protected\controllers\TasksController.php (18)
in Z:\home\yii\www\index.php (13)
2016/04/26 21:59:01 [error] [exception.CException] exception 'CException' with message 'Не определено свойство "Tasks.status".' in Z:\home\yii\www\framework\base\CComponent.php:130
Stack trace:
#0 Z:\home\yii\www\framework\db\ar\CActiveRecord.php(145): CComponent->__get('status')
#1 Z:\home\yii\www\framework\web\helpers\CHtml.php(2729): CActiveRecord->__get('status')
#2 Z:\home\yii\www\framework\web\helpers\CHtml.php(1923): CHtml::resolveValue(Object(Tasks), 'status')
#3 Z:\home\yii\www\protected\views\tasks\index.php(33): CHtml::activeCheckBox(Object(Tasks), 'status', Array)
#4 Z:\home\yii\www\framework\web\CBaseController.php(126): require('Z:\home\yii\www...')
#5 Z:\home\yii\www\framework\web\CBaseController.php(95): CBaseController->renderInternal('Z:\home\yii\www...', Array, true)
#6 Z:\home\yii\www\framework\web\CController.php(869): CBaseController->renderFile('Z:\home\yii\www...', Array, true)
#7 Z:\home\yii\www\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#8 Z:\home\yii\www\protected\controllers\TasksController.php(18): CController->render('index', Array)
#9 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionIndex()
#10 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 Z:\home\yii\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#12 Z:\home\yii\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('')
#14 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('tasks')
#15 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#16 Z:\home\yii\www\index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/index.php?r=tasks
HTTP_REFERER=http://www.yii/index.php?r=tasks
---
2016/04/26 21:59:07 [error] [exception.CException] exception 'CException' with message 'Не определено свойство "Tasks.status".' in Z:\home\yii\www\framework\base\CComponent.php:130
Stack trace:
#0 Z:\home\yii\www\framework\db\ar\CActiveRecord.php(145): CComponent->__get('status')
#1 Z:\home\yii\www\framework\web\helpers\CHtml.php(2729): CActiveRecord->__get('status')
#2 Z:\home\yii\www\framework\web\helpers\CHtml.php(1923): CHtml::resolveValue(Object(Tasks), 'status')
#3 Z:\home\yii\www\protected\views\tasks\index.php(33): CHtml::activeCheckBox(Object(Tasks), 'status', Array)
#4 Z:\home\yii\www\framework\web\CBaseController.php(126): require('Z:\home\yii\www...')
#5 Z:\home\yii\www\framework\web\CBaseController.php(95): CBaseController->renderInternal('Z:\home\yii\www...', Array, true)
#6 Z:\home\yii\www\framework\web\CController.php(869): CBaseController->renderFile('Z:\home\yii\www...', Array, true)
#7 Z:\home\yii\www\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#8 Z:\home\yii\www\protected\controllers\TasksController.php(18): CController->render('index', Array)
#9 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionIndex()
#10 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 Z:\home\yii\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#12 Z:\home\yii\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('')
#14 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('tasks')
#15 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#16 Z:\home\yii\www\index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/index.php?r=tasks
HTTP_REFERER=http://www.yii/index.php?r=tasks
---
2016/04/26 21:59:08 [error] [exception.CException] exception 'CException' with message 'Не определено свойство "Tasks.status".' in Z:\home\yii\www\framework\base\CComponent.php:130
Stack trace:
#0 Z:\home\yii\www\framework\db\ar\CActiveRecord.php(145): CComponent->__get('status')
#1 Z:\home\yii\www\framework\web\helpers\CHtml.php(2729): CActiveRecord->__get('status')
#2 Z:\home\yii\www\framework\web\helpers\CHtml.php(1923): CHtml::resolveValue(Object(Tasks), 'status')
#3 Z:\home\yii\www\protected\views\tasks\index.php(33): CHtml::activeCheckBox(Object(Tasks), 'status', Array)
#4 Z:\home\yii\www\framework\web\CBaseController.php(126): require('Z:\home\yii\www...')
#5 Z:\home\yii\www\framework\web\CBaseController.php(95): CBaseController->renderInternal('Z:\home\yii\www...', Array, true)
#6 Z:\home\yii\www\framework\web\CController.php(869): CBaseController->renderFile('Z:\home\yii\www...', Array, true)
#7 Z:\home\yii\www\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#8 Z:\home\yii\www\protected\controllers\TasksController.php(18): CController->render('index', Array)
#9 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionIndex()
#10 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 Z:\home\yii\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#12 Z:\home\yii\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('')
#14 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('tasks')
#15 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#16 Z:\home\yii\www\index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/index.php?r=tasks
HTTP_REFERER=http://www.yii/index.php?r=tasks
---
2016/04/27 12:40:31 [error] [php] Missing argument 1 for CActiveRecord::getAttribute(), called in Z:\home\yii\www\framework\base\CComponent.php on line 111 and defined (Z:\home\yii\www\framework\db\ar\CActiveRecord.php:694)
Stack trace:
#0 Z:\home\yii\www\framework\web\helpers\CHtml.php(2729): Tasks->__get()
#1 Z:\home\yii\www\framework\web\helpers\CHtml.php(2452): resolveValue()
#2 Z:\home\yii\www\framework\web\helpers\CHtml.php(1774): activeInputField()
#3 Z:\home\yii\www\protected\controllers\TasksController.php(20): activeTelField()
#4 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionIndex()
#5 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#6 Z:\home\yii\www\framework\web\CController.php(286): TasksController->runAction()
#7 Z:\home\yii\www\framework\web\CController.php(265): TasksController->runActionWithFilters()
#8 Z:\home\yii\www\framework\web\CWebApplication.php(282): TasksController->run()
#9 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#10 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#11 Z:\home\yii\www\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php?r=tasks/
in Z:\home\yii\www\protected\controllers\TasksController.php (20)
in Z:\home\yii\www\index.php (13)
2016/04/27 12:42:24 [error] [exception.CException] exception 'CException' with message 'Не определено свойство "Tasks.task1".' in Z:\home\yii\www\framework\base\CComponent.php:130
Stack trace:
#0 Z:\home\yii\www\framework\db\ar\CActiveRecord.php(145): CComponent->__get('task1')
#1 Z:\home\yii\www\framework\web\helpers\CHtml.php(2729): CActiveRecord->__get('task1')
#2 Z:\home\yii\www\framework\web\helpers\CHtml.php(2452): CHtml::resolveValue(Object(Tasks), 'task1')
#3 Z:\home\yii\www\framework\web\helpers\CHtml.php(1534): CHtml::activeInputField('text', Object(Tasks), 'task1', Array)
#4 Z:\home\yii\www\protected\controllers\TasksController.php(20): CHtml::activeTextField(Object(Tasks), 'task1', Array)
#5 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionIndex()
#6 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#7 Z:\home\yii\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#8 Z:\home\yii\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('')
#10 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('tasks/')
#11 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#12 Z:\home\yii\www\index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/index.php?r=tasks/
---
2016/04/27 12:43:24 [error] [exception.CException] exception 'CException' with message 'Не определено свойство "Tasks.0".' in Z:\home\yii\www\framework\base\CComponent.php:130
Stack trace:
#0 Z:\home\yii\www\framework\db\ar\CActiveRecord.php(145): CComponent->__get('0')
#1 Z:\home\yii\www\framework\base\CModel.php(596): CActiveRecord->__get('0')
#2 Z:\home\yii\www\protected\controllers\TasksController.php(20): CModel->offsetGet(0)
#3 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionIndex()
#4 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 Z:\home\yii\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#6 Z:\home\yii\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('')
#8 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('tasks/')
#9 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 Z:\home\yii\www\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/index.php?r=tasks/
---
2016/04/27 12:52:28 [error] [exception.CException] exception 'CException' with message 'Не определено свойство "Tasks.task1".' in Z:\home\yii\www\framework\base\CComponent.php:130
Stack trace:
#0 Z:\home\yii\www\framework\db\ar\CActiveRecord.php(145): CComponent->__get('task1')
#1 Z:\home\yii\www\framework\web\helpers\CHtml.php(2729): CActiveRecord->__get('task1')
#2 Z:\home\yii\www\framework\web\helpers\CHtml.php(2452): CHtml::resolveValue(Object(Tasks), 'task1')
#3 Z:\home\yii\www\framework\web\helpers\CHtml.php(1534): CHtml::activeInputField('text', Object(Tasks), 'task1', Array)
#4 Z:\home\yii\www\protected\controllers\TasksController.php(20): CHtml::activeTextField(Object(Tasks), 'task1', Array)
#5 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionIndex()
#6 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#7 Z:\home\yii\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#8 Z:\home\yii\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('')
#10 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('tasks/')
#11 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#12 Z:\home\yii\www\index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/index.php?r=tasks/
---
2016/04/28 13:35:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "task".' in Z:\home\yii\www\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('task')
#1 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 Z:\home\yii\www\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/task/
---
2016/04/28 13:35:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "rask".' in Z:\home\yii\www\framework\web\CController.php:483
Stack trace:
#0 Z:\home\yii\www\framework\web\CController.php(270): CController->missingAction('rask')
#1 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('rask')
#2 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('tasks/rask')
#3 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 Z:\home\yii\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/tasks/rask
---
2016/04/28 13:36:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "index.php".' in Z:\home\yii\www\framework\web\CController.php:483
Stack trace:
#0 Z:\home\yii\www\framework\web\CController.php(270): CController->missingAction('index.php')
#1 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('index.php')
#2 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('tasks/index.php...')
#3 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 Z:\home\yii\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/tasks/index.php/tasks/task?n=5
HTTP_REFERER=http://www.yii/index.php/tasks/
---
2016/04/28 13:37:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "index.php".' in Z:\home\yii\www\framework\web\CController.php:483
Stack trace:
#0 Z:\home\yii\www\framework\web\CController.php(270): CController->missingAction('index.php')
#1 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('index.php')
#2 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('tasks/index.php...')
#3 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 Z:\home\yii\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/tasks/index.php/tasks/task
HTTP_REFERER=http://www.yii/index.php/tasks/
---
2016/04/28 14:01:24 [error] [php] htmlspecialchars() expects parameter 1 to be string, array given (Z:\home\yii\www\framework\web\helpers\CHtml.php:108)
Stack trace:
#0 Z:\home\yii\www\framework\web\helpers\CHtml.php(163): renderAttributes()
#1 Z:\home\yii\www\framework\web\helpers\CHtml.php(1450): tag()
#2 Z:\home\yii\www\framework\web\helpers\CHtml.php(628): inputField()
#3 Z:\home\yii\www\protected\views\tasks\index.php(44): textField()
#4 Z:\home\yii\www\framework\web\CBaseController.php(126): require()
#5 Z:\home\yii\www\framework\web\CBaseController.php(95): TasksController->renderInternal()
#6 Z:\home\yii\www\framework\web\CController.php(869): TasksController->renderFile()
#7 Z:\home\yii\www\framework\web\CController.php(782): TasksController->renderPartial()
#8 Z:\home\yii\www\protected\controllers\TasksController.php(47): TasksController->render()
#9 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionIndex()
#10 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#11 Z:\home\yii\www\framework\web\CController.php(286): TasksController->runAction()
#12 Z:\home\yii\www\framework\web\CController.php(265): TasksController->runActionWithFilters()
#13 Z:\home\yii\www\framework\web\CWebApplication.php(282): TasksController->run()
#14 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#15 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#16 Z:\home\yii\www\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php/tasks/
in Z:\home\yii\www\protected\views\tasks\index.php (44)
in Z:\home\yii\www\protected\controllers\TasksController.php (47)
in Z:\home\yii\www\index.php (13)
2016/04/28 14:22:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "action".' in Z:\home\yii\www\framework\web\CController.php:483
Stack trace:
#0 Z:\home\yii\www\framework\web\CController.php(270): CController->missingAction('action')
#1 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('action')
#2 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('tasks/action')
#3 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 Z:\home\yii\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/tasks/action?num=1
HTTP_REFERER=http://www.yii/index.php/tasks/
---
2016/04/28 14:24:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "action".' in Z:\home\yii\www\framework\web\CController.php:483
Stack trace:
#0 Z:\home\yii\www\framework\web\CController.php(270): CController->missingAction('action')
#1 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('action')
#2 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('tasks/action')
#3 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 Z:\home\yii\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/tasks/action?num=1
HTTP_REFERER=http://www.yii/index.php/tasks/
---
2016/04/28 14:24:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "action".' in Z:\home\yii\www\framework\web\CController.php:483
Stack trace:
#0 Z:\home\yii\www\framework\web\CController.php(270): CController->missingAction('action')
#1 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('action')
#2 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('tasks/action')
#3 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 Z:\home\yii\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/tasks/action?num=1
HTTP_REFERER=http://www.yii/index.php/tasks/
---
2016/04/28 14:36:51 [error] [php] Invalid argument supplied for foreach() (Z:\home\yii\www\protected\views\tasks\task.php:25)
Stack trace:
#0 Z:\home\yii\www\framework\web\CController.php(869): TasksController->renderFile()
#1 Z:\home\yii\www\framework\web\CController.php(782): TasksController->renderPartial()
#2 Z:\home\yii\www\protected\controllers\TasksController.php(107): TasksController->render()
#3 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionTask()
#4 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 Z:\home\yii\www\framework\web\CController.php(286): TasksController->runAction()
#6 Z:\home\yii\www\framework\web\CController.php(265): TasksController->runActionWithFilters()
#7 Z:\home\yii\www\framework\web\CWebApplication.php(282): TasksController->run()
#8 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 Z:\home\yii\www\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php/tasks/task?num=1
in Z:\home\yii\www\protected\views\tasks\task.php (25)
in Z:\home\yii\www\protected\controllers\TasksController.php (107)
in Z:\home\yii\www\index.php (13)
2016/04/28 22:53:30 [error] [system.db.CDbCommand] Не удалось выполнить CDbCommand::fetchAll(): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'yii.fio' doesn't exist. Выполнявшийся SQL-запрос: SHOW FULL COLUMNS FROM `fio`.
in Z:\home\yii\www\protected\controllers\TasksController.php (10)
in Z:\home\yii\www\index.php (13)
2016/04/28 22:53:30 [error] [exception.CDbException] exception 'CDbException' with message 'Таблица "fio", упомянутая в записи active record класса "Fio", не найдена в базе данных.' in Z:\home\yii\www\framework\db\ar\CActiveRecord.php:2387
Stack trace:
#0 Z:\home\yii\www\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Fio))
#1 Z:\home\yii\www\framework\db\ar\CActiveRecord.php(79): CActiveRecord->getMetaData()
#2 Z:\home\yii\www\protected\controllers\TasksController.php(10): CActiveRecord->__construct()
#3 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionIndex()
#4 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 Z:\home\yii\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#6 Z:\home\yii\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('')
#8 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('tasks')
#9 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 Z:\home\yii\www\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/index.php/tasks
---
2016/04/28 22:53:36 [error] [system.db.CDbCommand] Не удалось выполнить CDbCommand::fetchAll(): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'yii.fio' doesn't exist. Выполнявшийся SQL-запрос: SHOW FULL COLUMNS FROM `fio`.
in Z:\home\yii\www\protected\controllers\TasksController.php (10)
in Z:\home\yii\www\index.php (13)
2016/04/28 22:53:36 [error] [exception.CDbException] exception 'CDbException' with message 'Таблица "fio", упомянутая в записи active record класса "Fio", не найдена в базе данных.' in Z:\home\yii\www\framework\db\ar\CActiveRecord.php:2387
Stack trace:
#0 Z:\home\yii\www\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Fio))
#1 Z:\home\yii\www\framework\db\ar\CActiveRecord.php(79): CActiveRecord->getMetaData()
#2 Z:\home\yii\www\protected\controllers\TasksController.php(10): CActiveRecord->__construct()
#3 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionIndex()
#4 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 Z:\home\yii\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#6 Z:\home\yii\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('')
#8 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('tasks')
#9 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 Z:\home\yii\www\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/index.php/tasks/
---
2016/04/29 10:32:51 [error] [exception.CException] exception 'CException' with message 'There is no CClientScript package: jquery-ui.js' in Z:\home\yii\www\framework\web\CClientScript.php:598
Stack trace:
#0 Z:\home\yii\www\protected\views\layouts\main.php(21): CClientScript->registerCoreScript('jquery-ui.js')
#1 Z:\home\yii\www\framework\web\CBaseController.php(126): require('Z:\home\yii\www...')
#2 Z:\home\yii\www\framework\web\CBaseController.php(95): CBaseController->renderInternal('Z:\home\yii\www...', Array, true)
#3 Z:\home\yii\www\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('Z:\home\yii\www...', Array, true)
#4 Z:\home\yii\www\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#5 Z:\home\yii\www\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#6 Z:\home\yii\www\framework\web\CBaseController.php(214): COutputProcessor->run()
#7 Z:\home\yii\www\framework\web\CBaseController.php(308): CBaseController->endWidget('CContentDecorat...')
#8 Z:\home\yii\www\protected\views\layouts\column1.php(6): CBaseController->endContent()
#9 Z:\home\yii\www\framework\web\CBaseController.php(126): require('Z:\home\yii\www...')
#10 Z:\home\yii\www\framework\web\CBaseController.php(95): CBaseController->renderInternal('Z:\home\yii\www...', Array, true)
#11 Z:\home\yii\www\framework\web\CController.php(784): CBaseController->renderFile('Z:\home\yii\www...', Array, true)
#12 Z:\home\yii\www\protected\controllers\TasksController.php(61): CController->render('index', Array)
#13 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionIndex()
#14 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#15 Z:\home\yii\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#16 Z:\home\yii\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('')
#18 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('tasks')
#19 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#20 Z:\home\yii\www\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/index.php/tasks/
---
2016/04/29 10:33:07 [error] [exception.CException] exception 'CException' with message 'There is no CClientScript package: jquery-ui' in Z:\home\yii\www\framework\web\CClientScript.php:598
Stack trace:
#0 Z:\home\yii\www\protected\views\layouts\main.php(21): CClientScript->registerCoreScript('jquery-ui')
#1 Z:\home\yii\www\framework\web\CBaseController.php(126): require('Z:\home\yii\www...')
#2 Z:\home\yii\www\framework\web\CBaseController.php(95): CBaseController->renderInternal('Z:\home\yii\www...', Array, true)
#3 Z:\home\yii\www\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('Z:\home\yii\www...', Array, true)
#4 Z:\home\yii\www\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#5 Z:\home\yii\www\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#6 Z:\home\yii\www\framework\web\CBaseController.php(214): COutputProcessor->run()
#7 Z:\home\yii\www\framework\web\CBaseController.php(308): CBaseController->endWidget('CContentDecorat...')
#8 Z:\home\yii\www\protected\views\layouts\column1.php(6): CBaseController->endContent()
#9 Z:\home\yii\www\framework\web\CBaseController.php(126): require('Z:\home\yii\www...')
#10 Z:\home\yii\www\framework\web\CBaseController.php(95): CBaseController->renderInternal('Z:\home\yii\www...', Array, true)
#11 Z:\home\yii\www\framework\web\CController.php(784): CBaseController->renderFile('Z:\home\yii\www...', Array, true)
#12 Z:\home\yii\www\protected\controllers\TasksController.php(61): CController->render('index', Array)
#13 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionIndex()
#14 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#15 Z:\home\yii\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#16 Z:\home\yii\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('')
#18 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('tasks')
#19 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#20 Z:\home\yii\www\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/index.php/tasks/
---
2016/04/29 10:35:27 [error] [exception.CException] exception 'CException' with message 'There is no CClientScript package: jquery.ui.js' in Z:\home\yii\www\framework\web\CClientScript.php:598
Stack trace:
#0 Z:\home\yii\www\protected\views\layouts\main.php(21): CClientScript->registerCoreScript('jquery.ui.js')
#1 Z:\home\yii\www\framework\web\CBaseController.php(126): require('Z:\home\yii\www...')
#2 Z:\home\yii\www\framework\web\CBaseController.php(95): CBaseController->renderInternal('Z:\home\yii\www...', Array, true)
#3 Z:\home\yii\www\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('Z:\home\yii\www...', Array, true)
#4 Z:\home\yii\www\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#5 Z:\home\yii\www\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#6 Z:\home\yii\www\framework\web\CBaseController.php(214): COutputProcessor->run()
#7 Z:\home\yii\www\framework\web\CBaseController.php(308): CBaseController->endWidget('CContentDecorat...')
#8 Z:\home\yii\www\protected\views\layouts\column1.php(6): CBaseController->endContent()
#9 Z:\home\yii\www\framework\web\CBaseController.php(126): require('Z:\home\yii\www...')
#10 Z:\home\yii\www\framework\web\CBaseController.php(95): CBaseController->renderInternal('Z:\home\yii\www...', Array, true)
#11 Z:\home\yii\www\framework\web\CController.php(784): CBaseController->renderFile('Z:\home\yii\www...', Array, true)
#12 Z:\home\yii\www\protected\controllers\TasksController.php(61): CController->render('index', Array)
#13 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionIndex()
#14 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#15 Z:\home\yii\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#16 Z:\home\yii\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('')
#18 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('tasks')
#19 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#20 Z:\home\yii\www\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/index.php/tasks/
---
2016/04/29 12:43:24 [error] [exception.CException] exception 'CException' with message 'There is no CClientScript package: jquery.validate.min' in Z:\home\yii\www\framework\web\CClientScript.php:598
Stack trace:
#0 Z:\home\yii\www\protected\views\layouts\main.php(22): CClientScript->registerCoreScript('jquery.validate...')
#1 Z:\home\yii\www\framework\web\CBaseController.php(126): require('Z:\home\yii\www...')
#2 Z:\home\yii\www\framework\web\CBaseController.php(95): CBaseController->renderInternal('Z:\home\yii\www...', Array, true)
#3 Z:\home\yii\www\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('Z:\home\yii\www...', Array, true)
#4 Z:\home\yii\www\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#5 Z:\home\yii\www\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#6 Z:\home\yii\www\framework\web\CBaseController.php(214): COutputProcessor->run()
#7 Z:\home\yii\www\framework\web\CBaseController.php(308): CBaseController->endWidget('CContentDecorat...')
#8 Z:\home\yii\www\protected\views\layouts\column1.php(6): CBaseController->endContent()
#9 Z:\home\yii\www\framework\web\CBaseController.php(126): require('Z:\home\yii\www...')
#10 Z:\home\yii\www\framework\web\CBaseController.php(95): CBaseController->renderInternal('Z:\home\yii\www...', Array, true)
#11 Z:\home\yii\www\framework\web\CController.php(784): CBaseController->renderFile('Z:\home\yii\www...', Array, true)
#12 Z:\home\yii\www\protected\controllers\TasksController.php(61): CController->render('index', Array)
#13 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionIndex()
#14 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#15 Z:\home\yii\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#16 Z:\home\yii\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('')
#18 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('tasks')
#19 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#20 Z:\home\yii\www\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/index.php/tasks/
---
2016/04/29 12:43:32 [error] [exception.CException] exception 'CException' with message 'There is no CClientScript package: jquery.validate.min' in Z:\home\yii\www\framework\web\CClientScript.php:598
Stack trace:
#0 Z:\home\yii\www\protected\views\layouts\main.php(22): CClientScript->registerCoreScript('jquery.validate...')
#1 Z:\home\yii\www\framework\web\CBaseController.php(126): require('Z:\home\yii\www...')
#2 Z:\home\yii\www\framework\web\CBaseController.php(95): CBaseController->renderInternal('Z:\home\yii\www...', Array, true)
#3 Z:\home\yii\www\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('Z:\home\yii\www...', Array, true)
#4 Z:\home\yii\www\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#5 Z:\home\yii\www\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#6 Z:\home\yii\www\framework\web\CBaseController.php(214): COutputProcessor->run()
#7 Z:\home\yii\www\framework\web\CBaseController.php(308): CBaseController->endWidget('CContentDecorat...')
#8 Z:\home\yii\www\protected\views\layouts\column1.php(6): CBaseController->endContent()
#9 Z:\home\yii\www\framework\web\CBaseController.php(126): require('Z:\home\yii\www...')
#10 Z:\home\yii\www\framework\web\CBaseController.php(95): CBaseController->renderInternal('Z:\home\yii\www...', Array, true)
#11 Z:\home\yii\www\framework\web\CController.php(784): CBaseController->renderFile('Z:\home\yii\www...', Array, true)
#12 Z:\home\yii\www\protected\controllers\TasksController.php(141): CController->render('task', Array)
#13 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionTask()
#14 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#15 Z:\home\yii\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#16 Z:\home\yii\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('task')
#18 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('tasks/task')
#19 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#20 Z:\home\yii\www\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/index.php/tasks/task?num=7
HTTP_REFERER=http://www.yii/index.php/tasks/
---
2016/04/29 13:05:01 [error] [exception.CException] exception 'CException' with message 'There is no CClientScript package: jquery.validate.min' in Z:\home\yii\www\framework\web\CClientScript.php:598
Stack trace:
#0 Z:\home\yii\www\protected\views\layouts\main.php(21): CClientScript->registerCoreScript('jquery.validate...')
#1 Z:\home\yii\www\framework\web\CBaseController.php(126): require('Z:\home\yii\www...')
#2 Z:\home\yii\www\framework\web\CBaseController.php(95): CBaseController->renderInternal('Z:\home\yii\www...', Array, true)
#3 Z:\home\yii\www\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('Z:\home\yii\www...', Array, true)
#4 Z:\home\yii\www\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#5 Z:\home\yii\www\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#6 Z:\home\yii\www\framework\web\CBaseController.php(214): COutputProcessor->run()
#7 Z:\home\yii\www\framework\web\CBaseController.php(308): CBaseController->endWidget('CContentDecorat...')
#8 Z:\home\yii\www\protected\views\layouts\column1.php(6): CBaseController->endContent()
#9 Z:\home\yii\www\framework\web\CBaseController.php(126): require('Z:\home\yii\www...')
#10 Z:\home\yii\www\framework\web\CBaseController.php(95): CBaseController->renderInternal('Z:\home\yii\www...', Array, true)
#11 Z:\home\yii\www\framework\web\CController.php(784): CBaseController->renderFile('Z:\home\yii\www...', Array, true)
#12 Z:\home\yii\www\protected\controllers\TasksController.php(61): CController->render('index', Array)
#13 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionIndex()
#14 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#15 Z:\home\yii\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#16 Z:\home\yii\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('')
#18 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('tasks')
#19 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#20 Z:\home\yii\www\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/index.php/tasks/
---
2016/04/29 13:06:12 [error] [exception.CException] exception 'CException' with message 'There is no CClientScript package: jquery.validate.min' in Z:\home\yii\www\framework\web\CClientScript.php:598
Stack trace:
#0 Z:\home\yii\www\protected\views\layouts\main.php(21): CClientScript->registerCoreScript('jquery.validate...')
#1 Z:\home\yii\www\framework\web\CBaseController.php(126): require('Z:\home\yii\www...')
#2 Z:\home\yii\www\framework\web\CBaseController.php(95): CBaseController->renderInternal('Z:\home\yii\www...', Array, true)
#3 Z:\home\yii\www\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('Z:\home\yii\www...', Array, true)
#4 Z:\home\yii\www\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#5 Z:\home\yii\www\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#6 Z:\home\yii\www\framework\web\CBaseController.php(214): COutputProcessor->run()
#7 Z:\home\yii\www\framework\web\CBaseController.php(308): CBaseController->endWidget('CContentDecorat...')
#8 Z:\home\yii\www\protected\views\layouts\column1.php(6): CBaseController->endContent()
#9 Z:\home\yii\www\framework\web\CBaseController.php(126): require('Z:\home\yii\www...')
#10 Z:\home\yii\www\framework\web\CBaseController.php(95): CBaseController->renderInternal('Z:\home\yii\www...', Array, true)
#11 Z:\home\yii\www\framework\web\CController.php(784): CBaseController->renderFile('Z:\home\yii\www...', Array, true)
#12 Z:\home\yii\www\protected\controllers\TasksController.php(61): CController->render('index', Array)
#13 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionIndex()
#14 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#15 Z:\home\yii\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#16 Z:\home\yii\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('')
#18 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('tasks')
#19 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#20 Z:\home\yii\www\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/index.php/tasks/
---
2016/04/29 13:07:25 [error] [exception.CException] exception 'CException' with message 'There is no CClientScript package: jquery.validate.min' in Z:\home\yii\www\framework\web\CClientScript.php:598
Stack trace:
#0 Z:\home\yii\www\protected\views\layouts\main.php(7): CClientScript->registerCoreScript('jquery.validate...')
#1 Z:\home\yii\www\framework\web\CBaseController.php(126): require('Z:\home\yii\www...')
#2 Z:\home\yii\www\framework\web\CBaseController.php(95): CBaseController->renderInternal('Z:\home\yii\www...', Array, true)
#3 Z:\home\yii\www\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('Z:\home\yii\www...', Array, true)
#4 Z:\home\yii\www\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#5 Z:\home\yii\www\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#6 Z:\home\yii\www\framework\web\CBaseController.php(214): COutputProcessor->run()
#7 Z:\home\yii\www\framework\web\CBaseController.php(308): CBaseController->endWidget('CContentDecorat...')
#8 Z:\home\yii\www\protected\views\layouts\column1.php(6): CBaseController->endContent()
#9 Z:\home\yii\www\framework\web\CBaseController.php(126): require('Z:\home\yii\www...')
#10 Z:\home\yii\www\framework\web\CBaseController.php(95): CBaseController->renderInternal('Z:\home\yii\www...', Array, true)
#11 Z:\home\yii\www\framework\web\CController.php(784): CBaseController->renderFile('Z:\home\yii\www...', Array, true)
#12 Z:\home\yii\www\protected\controllers\TasksController.php(61): CController->render('index', Array)
#13 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionIndex()
#14 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#15 Z:\home\yii\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#16 Z:\home\yii\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('')
#18 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('tasks')
#19 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#20 Z:\home\yii\www\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/index.php/tasks/
---
2016/04/29 13:09:34 [error] [exception.CException] exception 'CException' with message 'There is no CClientScript package: jquery.validate.min' in Z:\home\yii\www\framework\web\CClientScript.php:598
Stack trace:
#0 Z:\home\yii\www\protected\views\layouts\main.php(7): CClientScript->registerCoreScript('jquery.validate...')
#1 Z:\home\yii\www\framework\web\CBaseController.php(126): require('Z:\home\yii\www...')
#2 Z:\home\yii\www\framework\web\CBaseController.php(95): CBaseController->renderInternal('Z:\home\yii\www...', Array, true)
#3 Z:\home\yii\www\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('Z:\home\yii\www...', Array, true)
#4 Z:\home\yii\www\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#5 Z:\home\yii\www\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#6 Z:\home\yii\www\framework\web\CBaseController.php(214): COutputProcessor->run()
#7 Z:\home\yii\www\framework\web\CBaseController.php(308): CBaseController->endWidget('CContentDecorat...')
#8 Z:\home\yii\www\protected\views\layouts\column1.php(6): CBaseController->endContent()
#9 Z:\home\yii\www\framework\web\CBaseController.php(126): require('Z:\home\yii\www...')
#10 Z:\home\yii\www\framework\web\CBaseController.php(95): CBaseController->renderInternal('Z:\home\yii\www...', Array, true)
#11 Z:\home\yii\www\framework\web\CController.php(784): CBaseController->renderFile('Z:\home\yii\www...', Array, true)
#12 Z:\home\yii\www\protected\controllers\TasksController.php(61): CController->render('index', Array)
#13 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionIndex()
#14 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#15 Z:\home\yii\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#16 Z:\home\yii\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('')
#18 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('tasks')
#19 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#20 Z:\home\yii\www\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/index.php/tasks/
---
2016/04/29 13:11:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "jquery.validate.min.js".' in Z:\home\yii\www\framework\web\CController.php:483
Stack trace:
#0 Z:\home\yii\www\framework\web\CController.php(270): CController->missingAction('jquery.validate...')
#1 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('jquery.validate...')
#2 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('tasks/jquery.va...')
#3 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 Z:\home\yii\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/tasks/jquery.validate.min.js
HTTP_REFERER=http://www.yii/index.php/tasks/
---
2016/05/02 11:57:22 [error] [exception.CException] exception 'CException' with message 'Контроллер TasksController не может найти представление "Tasks_form".' in Z:\home\yii\www\framework\web\CController.php:878
Stack trace:
#0 Z:\home\yii\www\framework\web\CController.php(782): CController->renderPartial('Tasks_form', Array, true)
#1 Z:\home\yii\www\protected\controllers\TasksController.php(28): CController->render('Tasks_form', Array)
#2 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionTasks_form()
#3 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 Z:\home\yii\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 Z:\home\yii\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('tasks_form')
#7 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('tasks/tasks_for...')
#8 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#9 Z:\home\yii\www\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/index.php/tasks/tasks_form
---
2016/05/02 13:46:24 [error] [exception.CException] exception 'CException' with message 'Не определено свойство "Tasks.vd".' in Z:\home\yii\www\framework\base\CComponent.php:130
Stack trace:
#0 Z:\home\yii\www\framework\db\ar\CActiveRecord.php(145): CComponent->__get('vd')
#1 Z:\home\yii\www\protected\models\Tasks.php(43): CActiveRecord->__get('vd')
#2 Z:\home\yii\www\framework\validators\CInlineValidator.php(42): Tasks->valid_date('deadline', Array)
#3 Z:\home\yii\www\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(Tasks), 'deadline')
#4 Z:\home\yii\www\framework\base\CModel.php(159): CValidator->validate(Object(Tasks), NULL)
#5 Z:\home\yii\www\framework\web\widgets\CActiveForm.php(987): CModel->validate(NULL)
#6 Z:\home\yii\www\protected\controllers\TasksController.php(14): CActiveForm::validate(Object(Tasks))
#7 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionTasks_form()
#8 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 Z:\home\yii\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 Z:\home\yii\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('tasks_form')
#12 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('tasks/tasks_for...')
#13 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#14 Z:\home\yii\www\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/index.php/tasks/tasks_form
HTTP_REFERER=http://www.yii/index.php/tasks/tasks_form
---
2016/05/02 13:46:26 [error] [exception.CException] exception 'CException' with message 'Не определено свойство "Tasks.vd".' in Z:\home\yii\www\framework\base\CComponent.php:130
Stack trace:
#0 Z:\home\yii\www\framework\db\ar\CActiveRecord.php(145): CComponent->__get('vd')
#1 Z:\home\yii\www\protected\models\Tasks.php(43): CActiveRecord->__get('vd')
#2 Z:\home\yii\www\framework\validators\CInlineValidator.php(42): Tasks->valid_date('deadline', Array)
#3 Z:\home\yii\www\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(Tasks), 'deadline')
#4 Z:\home\yii\www\framework\base\CModel.php(159): CValidator->validate(Object(Tasks), NULL)
#5 Z:\home\yii\www\framework\web\widgets\CActiveForm.php(987): CModel->validate(NULL)
#6 Z:\home\yii\www\protected\controllers\TasksController.php(14): CActiveForm::validate(Object(Tasks))
#7 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionTasks_form()
#8 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 Z:\home\yii\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 Z:\home\yii\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('tasks_form')
#12 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('tasks/tasks_for...')
#13 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#14 Z:\home\yii\www\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/index.php/tasks/tasks_form
HTTP_REFERER=http://www.yii/index.php/tasks/tasks_form
---
2016/05/02 13:46:27 [error] [exception.CException] exception 'CException' with message 'Не определено свойство "Tasks.vd".' in Z:\home\yii\www\framework\base\CComponent.php:130
Stack trace:
#0 Z:\home\yii\www\framework\db\ar\CActiveRecord.php(145): CComponent->__get('vd')
#1 Z:\home\yii\www\protected\models\Tasks.php(43): CActiveRecord->__get('vd')
#2 Z:\home\yii\www\framework\validators\CInlineValidator.php(42): Tasks->valid_date('deadline', Array)
#3 Z:\home\yii\www\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(Tasks), 'deadline')
#4 Z:\home\yii\www\framework\base\CModel.php(159): CValidator->validate(Object(Tasks), NULL)
#5 Z:\home\yii\www\framework\web\widgets\CActiveForm.php(987): CModel->validate(NULL)
#6 Z:\home\yii\www\protected\controllers\TasksController.php(14): CActiveForm::validate(Object(Tasks))
#7 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionTasks_form()
#8 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 Z:\home\yii\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 Z:\home\yii\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('tasks_form')
#12 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('tasks/tasks_for...')
#13 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#14 Z:\home\yii\www\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/index.php/tasks/tasks_form
HTTP_REFERER=http://www.yii/index.php/tasks/tasks_form
---
2016/05/02 13:46:28 [error] [exception.CException] exception 'CException' with message 'Не определено свойство "Tasks.vd".' in Z:\home\yii\www\framework\base\CComponent.php:130
Stack trace:
#0 Z:\home\yii\www\framework\db\ar\CActiveRecord.php(145): CComponent->__get('vd')
#1 Z:\home\yii\www\protected\models\Tasks.php(43): CActiveRecord->__get('vd')
#2 Z:\home\yii\www\framework\validators\CInlineValidator.php(42): Tasks->valid_date('deadline', Array)
#3 Z:\home\yii\www\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(Tasks), 'deadline')
#4 Z:\home\yii\www\framework\base\CModel.php(159): CValidator->validate(Object(Tasks), NULL)
#5 Z:\home\yii\www\framework\web\widgets\CActiveForm.php(987): CModel->validate(NULL)
#6 Z:\home\yii\www\protected\controllers\TasksController.php(14): CActiveForm::validate(Object(Tasks))
#7 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionTasks_form()
#8 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 Z:\home\yii\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 Z:\home\yii\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('tasks_form')
#12 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('tasks/tasks_for...')
#13 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#14 Z:\home\yii\www\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/index.php/tasks/tasks_form
HTTP_REFERER=http://www.yii/index.php/tasks/tasks_form
---
2016/05/02 13:46:29 [error] [exception.CException] exception 'CException' with message 'Не определено свойство "Tasks.vd".' in Z:\home\yii\www\framework\base\CComponent.php:130
Stack trace:
#0 Z:\home\yii\www\framework\db\ar\CActiveRecord.php(145): CComponent->__get('vd')
#1 Z:\home\yii\www\protected\models\Tasks.php(43): CActiveRecord->__get('vd')
#2 Z:\home\yii\www\framework\validators\CInlineValidator.php(42): Tasks->valid_date('deadline', Array)
#3 Z:\home\yii\www\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(Tasks), 'deadline')
#4 Z:\home\yii\www\framework\base\CModel.php(159): CValidator->validate(Object(Tasks), NULL)
#5 Z:\home\yii\www\framework\web\widgets\CActiveForm.php(987): CModel->validate(NULL)
#6 Z:\home\yii\www\protected\controllers\TasksController.php(14): CActiveForm::validate(Object(Tasks))
#7 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionTasks_form()
#8 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 Z:\home\yii\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 Z:\home\yii\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('tasks_form')
#12 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('tasks/tasks_for...')
#13 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#14 Z:\home\yii\www\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/index.php/tasks/tasks_form
HTTP_REFERER=http://www.yii/index.php/tasks/tasks_form
---
2016/05/02 13:46:31 [error] [exception.CException] exception 'CException' with message 'Не определено свойство "Tasks.vd".' in Z:\home\yii\www\framework\base\CComponent.php:130
Stack trace:
#0 Z:\home\yii\www\framework\db\ar\CActiveRecord.php(145): CComponent->__get('vd')
#1 Z:\home\yii\www\protected\models\Tasks.php(43): CActiveRecord->__get('vd')
#2 Z:\home\yii\www\framework\validators\CInlineValidator.php(42): Tasks->valid_date('deadline', Array)
#3 Z:\home\yii\www\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(Tasks), 'deadline')
#4 Z:\home\yii\www\framework\base\CModel.php(159): CValidator->validate(Object(Tasks), NULL)
#5 Z:\home\yii\www\framework\web\widgets\CActiveForm.php(987): CModel->validate(NULL)
#6 Z:\home\yii\www\protected\controllers\TasksController.php(14): CActiveForm::validate(Object(Tasks))
#7 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionTasks_form()
#8 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 Z:\home\yii\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 Z:\home\yii\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('tasks_form')
#12 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('tasks/tasks_for...')
#13 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#14 Z:\home\yii\www\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/index.php/tasks/tasks_form
HTTP_REFERER=http://www.yii/index.php/tasks/tasks_form
---
2016/05/02 13:46:32 [error] [exception.CException] exception 'CException' with message 'Не определено свойство "Tasks.vd".' in Z:\home\yii\www\framework\base\CComponent.php:130
Stack trace:
#0 Z:\home\yii\www\framework\db\ar\CActiveRecord.php(145): CComponent->__get('vd')
#1 Z:\home\yii\www\protected\models\Tasks.php(43): CActiveRecord->__get('vd')
#2 Z:\home\yii\www\framework\validators\CInlineValidator.php(42): Tasks->valid_date('deadline', Array)
#3 Z:\home\yii\www\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(Tasks), 'deadline')
#4 Z:\home\yii\www\framework\base\CModel.php(159): CValidator->validate(Object(Tasks), NULL)
#5 Z:\home\yii\www\framework\web\widgets\CActiveForm.php(987): CModel->validate(NULL)
#6 Z:\home\yii\www\protected\controllers\TasksController.php(14): CActiveForm::validate(Object(Tasks))
#7 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionTasks_form()
#8 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 Z:\home\yii\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 Z:\home\yii\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('tasks_form')
#12 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('tasks/tasks_for...')
#13 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#14 Z:\home\yii\www\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/index.php/tasks/tasks_form
HTTP_REFERER=http://www.yii/index.php/tasks/tasks_form
---
2016/05/02 13:46:33 [error] [exception.CException] exception 'CException' with message 'Не определено свойство "Tasks.vd".' in Z:\home\yii\www\framework\base\CComponent.php:130
Stack trace:
#0 Z:\home\yii\www\framework\db\ar\CActiveRecord.php(145): CComponent->__get('vd')
#1 Z:\home\yii\www\protected\models\Tasks.php(43): CActiveRecord->__get('vd')
#2 Z:\home\yii\www\framework\validators\CInlineValidator.php(42): Tasks->valid_date('deadline', Array)
#3 Z:\home\yii\www\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(Tasks), 'deadline')
#4 Z:\home\yii\www\framework\base\CModel.php(159): CValidator->validate(Object(Tasks), NULL)
#5 Z:\home\yii\www\framework\web\widgets\CActiveForm.php(987): CModel->validate(NULL)
#6 Z:\home\yii\www\protected\controllers\TasksController.php(14): CActiveForm::validate(Object(Tasks))
#7 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionTasks_form()
#8 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 Z:\home\yii\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 Z:\home\yii\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('tasks_form')
#12 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('tasks/tasks_for...')
#13 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#14 Z:\home\yii\www\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/index.php/tasks/tasks_form
HTTP_REFERER=http://www.yii/index.php/tasks/tasks_form
---
2016/05/02 13:46:33 [error] [exception.CException] exception 'CException' with message 'Не определено свойство "Tasks.vd".' in Z:\home\yii\www\framework\base\CComponent.php:130
Stack trace:
#0 Z:\home\yii\www\framework\db\ar\CActiveRecord.php(145): CComponent->__get('vd')
#1 Z:\home\yii\www\protected\models\Tasks.php(43): CActiveRecord->__get('vd')
#2 Z:\home\yii\www\framework\validators\CInlineValidator.php(42): Tasks->valid_date('deadline', Array)
#3 Z:\home\yii\www\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(Tasks), 'deadline')
#4 Z:\home\yii\www\framework\base\CModel.php(159): CValidator->validate(Object(Tasks), NULL)
#5 Z:\home\yii\www\framework\web\widgets\CActiveForm.php(987): CModel->validate(NULL)
#6 Z:\home\yii\www\protected\controllers\TasksController.php(14): CActiveForm::validate(Object(Tasks))
#7 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionTasks_form()
#8 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 Z:\home\yii\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 Z:\home\yii\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('tasks_form')
#12 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('tasks/tasks_for...')
#13 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#14 Z:\home\yii\www\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/index.php/tasks/tasks_form
HTTP_REFERER=http://www.yii/index.php/tasks/tasks_form
---
2016/05/02 13:46:34 [error] [exception.CException] exception 'CException' with message 'Не определено свойство "Tasks.vd".' in Z:\home\yii\www\framework\base\CComponent.php:130
Stack trace:
#0 Z:\home\yii\www\framework\db\ar\CActiveRecord.php(145): CComponent->__get('vd')
#1 Z:\home\yii\www\protected\models\Tasks.php(43): CActiveRecord->__get('vd')
#2 Z:\home\yii\www\framework\validators\CInlineValidator.php(42): Tasks->valid_date('deadline', Array)
#3 Z:\home\yii\www\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(Tasks), 'deadline')
#4 Z:\home\yii\www\framework\base\CModel.php(159): CValidator->validate(Object(Tasks), NULL)
#5 Z:\home\yii\www\framework\web\widgets\CActiveForm.php(987): CModel->validate(NULL)
#6 Z:\home\yii\www\protected\controllers\TasksController.php(14): CActiveForm::validate(Object(Tasks))
#7 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionTasks_form()
#8 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 Z:\home\yii\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 Z:\home\yii\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('tasks_form')
#12 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('tasks/tasks_for...')
#13 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#14 Z:\home\yii\www\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/index.php/tasks/tasks_form
HTTP_REFERER=http://www.yii/index.php/tasks/tasks_form
---
2016/05/02 13:46:34 [error] [exception.CException] exception 'CException' with message 'Не определено свойство "Tasks.vd".' in Z:\home\yii\www\framework\base\CComponent.php:130
Stack trace:
#0 Z:\home\yii\www\framework\db\ar\CActiveRecord.php(145): CComponent->__get('vd')
#1 Z:\home\yii\www\protected\models\Tasks.php(43): CActiveRecord->__get('vd')
#2 Z:\home\yii\www\framework\validators\CInlineValidator.php(42): Tasks->valid_date('deadline', Array)
#3 Z:\home\yii\www\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(Tasks), 'deadline')
#4 Z:\home\yii\www\framework\base\CModel.php(159): CValidator->validate(Object(Tasks), NULL)
#5 Z:\home\yii\www\framework\web\widgets\CActiveForm.php(987): CModel->validate(NULL)
#6 Z:\home\yii\www\protected\controllers\TasksController.php(14): CActiveForm::validate(Object(Tasks))
#7 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionTasks_form()
#8 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 Z:\home\yii\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 Z:\home\yii\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('tasks_form')
#12 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('tasks/tasks_for...')
#13 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#14 Z:\home\yii\www\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/index.php/tasks/tasks_form
HTTP_REFERER=http://www.yii/index.php/tasks/tasks_form
---
2016/05/02 15:02:42 [error] [exception.CException] exception 'CException' with message 'Не определено свойство "Tasks.".' in Z:\home\yii\www\framework\base\CComponent.php:130
Stack trace:
#0 Z:\home\yii\www\framework\db\ar\CActiveRecord.php(145): CComponent->__get('')
#1 Z:\home\yii\www\framework\web\helpers\CHtml.php(2729): CActiveRecord->__get('')
#2 Z:\home\yii\www\framework\web\helpers\CHtml.php(2452): CHtml::resolveValue(Object(Tasks), '')
#3 Z:\home\yii\www\framework\web\helpers\CHtml.php(1654): CHtml::activeInputField('date', Object(Tasks), '', Array)
#4 Z:\home\yii\www\framework\web\widgets\CActiveForm.php(680): CHtml::activeDateField(Object(Tasks), '', Array)
#5 Z:\home\yii\www\protected\views\tasks\index.php(120): CActiveForm->dateField(Object(Tasks), '', Array)
#6 Z:\home\yii\www\framework\web\CBaseController.php(126): require('Z:\home\yii\www...')
#7 Z:\home\yii\www\framework\web\CBaseController.php(95): CBaseController->renderInternal('Z:\home\yii\www...', Array, true)
#8 Z:\home\yii\www\framework\web\CController.php(869): CBaseController->renderFile('Z:\home\yii\www...', Array, true)
#9 Z:\home\yii\www\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#10 Z:\home\yii\www\protected\controllers\TasksController.php(110): CController->render('index', Array)
#11 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionIndex()
#12 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#13 Z:\home\yii\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#14 Z:\home\yii\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('')
#16 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('tasks')
#17 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#18 Z:\home\yii\www\index.php(13): CApplication->run()
#19 {main}
REQUEST_URI=/index.php/tasks/
---
2016/05/02 15:03:11 [error] [exception.CException] exception 'CException' with message 'Не определено свойство "Tasks.".' in Z:\home\yii\www\framework\base\CComponent.php:130
Stack trace:
#0 Z:\home\yii\www\framework\db\ar\CActiveRecord.php(145): CComponent->__get('')
#1 Z:\home\yii\www\framework\web\helpers\CHtml.php(2729): CActiveRecord->__get('')
#2 Z:\home\yii\www\framework\web\helpers\CHtml.php(2452): CHtml::resolveValue(Object(Tasks), '')
#3 Z:\home\yii\www\framework\web\helpers\CHtml.php(1654): CHtml::activeInputField('date', Object(Tasks), '', Array)
#4 Z:\home\yii\www\framework\web\widgets\CActiveForm.php(680): CHtml::activeDateField(Object(Tasks), '', Array)
#5 Z:\home\yii\www\protected\views\tasks\index.php(120): CActiveForm->dateField(Object(Tasks), '', Array)
#6 Z:\home\yii\www\framework\web\CBaseController.php(126): require('Z:\home\yii\www...')
#7 Z:\home\yii\www\framework\web\CBaseController.php(95): CBaseController->renderInternal('Z:\home\yii\www...', Array, true)
#8 Z:\home\yii\www\framework\web\CController.php(869): CBaseController->renderFile('Z:\home\yii\www...', Array, true)
#9 Z:\home\yii\www\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#10 Z:\home\yii\www\protected\controllers\TasksController.php(110): CController->render('index', Array)
#11 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionIndex()
#12 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#13 Z:\home\yii\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#14 Z:\home\yii\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('')
#16 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('tasks')
#17 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#18 Z:\home\yii\www\index.php(13): CApplication->run()
#19 {main}
REQUEST_URI=/index.php/tasks/
---
2016/05/02 15:03:22 [error] [exception.CException] exception 'CException' with message 'Не определено свойство "Tasks.".' in Z:\home\yii\www\framework\base\CComponent.php:130
Stack trace:
#0 Z:\home\yii\www\framework\db\ar\CActiveRecord.php(145): CComponent->__get('')
#1 Z:\home\yii\www\framework\web\helpers\CHtml.php(2729): CActiveRecord->__get('')
#2 Z:\home\yii\www\framework\web\helpers\CHtml.php(2452): CHtml::resolveValue(Object(Tasks), '')
#3 Z:\home\yii\www\framework\web\helpers\CHtml.php(1654): CHtml::activeInputField('date', Object(Tasks), '', Array)
#4 Z:\home\yii\www\framework\web\widgets\CActiveForm.php(680): CHtml::activeDateField(Object(Tasks), '', '')
#5 Z:\home\yii\www\protected\views\tasks\index.php(120): CActiveForm->dateField(Object(Tasks), '', '')
#6 Z:\home\yii\www\framework\web\CBaseController.php(126): require('Z:\home\yii\www...')
#7 Z:\home\yii\www\framework\web\CBaseController.php(95): CBaseController->renderInternal('Z:\home\yii\www...', Array, true)
#8 Z:\home\yii\www\framework\web\CController.php(869): CBaseController->renderFile('Z:\home\yii\www...', Array, true)
#9 Z:\home\yii\www\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#10 Z:\home\yii\www\protected\controllers\TasksController.php(110): CController->render('index', Array)
#11 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionIndex()
#12 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#13 Z:\home\yii\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#14 Z:\home\yii\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('')
#16 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('tasks')
#17 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#18 Z:\home\yii\www\index.php(13): CApplication->run()
#19 {main}
REQUEST_URI=/index.php/tasks/
---
2016/05/02 15:03:25 [error] [exception.CException] exception 'CException' with message 'Не определено свойство "Tasks.".' in Z:\home\yii\www\framework\base\CComponent.php:130
Stack trace:
#0 Z:\home\yii\www\framework\db\ar\CActiveRecord.php(145): CComponent->__get('')
#1 Z:\home\yii\www\framework\web\helpers\CHtml.php(2729): CActiveRecord->__get('')
#2 Z:\home\yii\www\framework\web\helpers\CHtml.php(2452): CHtml::resolveValue(Object(Tasks), '')
#3 Z:\home\yii\www\framework\web\helpers\CHtml.php(1654): CHtml::activeInputField('date', Object(Tasks), '', Array)
#4 Z:\home\yii\www\framework\web\widgets\CActiveForm.php(680): CHtml::activeDateField(Object(Tasks), '', '')
#5 Z:\home\yii\www\protected\views\tasks\index.php(120): CActiveForm->dateField(Object(Tasks), '', '')
#6 Z:\home\yii\www\framework\web\CBaseController.php(126): require('Z:\home\yii\www...')
#7 Z:\home\yii\www\framework\web\CBaseController.php(95): CBaseController->renderInternal('Z:\home\yii\www...', Array, true)
#8 Z:\home\yii\www\framework\web\CController.php(869): CBaseController->renderFile('Z:\home\yii\www...', Array, true)
#9 Z:\home\yii\www\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#10 Z:\home\yii\www\protected\controllers\TasksController.php(110): CController->render('index', Array)
#11 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionIndex()
#12 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#13 Z:\home\yii\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#14 Z:\home\yii\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('')
#16 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('tasks')
#17 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#18 Z:\home\yii\www\index.php(13): CApplication->run()
#19 {main}
REQUEST_URI=/index.php/tasks/
---
2016/05/02 15:03:45 [error] [exception.CException] exception 'CException' with message 'Не определено свойство "Tasks.deadline1".' in Z:\home\yii\www\framework\base\CComponent.php:130
Stack trace:
#0 Z:\home\yii\www\framework\db\ar\CActiveRecord.php(145): CComponent->__get('deadline1')
#1 Z:\home\yii\www\framework\web\helpers\CHtml.php(2729): CActiveRecord->__get('deadline1')
#2 Z:\home\yii\www\framework\web\helpers\CHtml.php(2452): CHtml::resolveValue(Object(Tasks), 'deadline1')
#3 Z:\home\yii\www\framework\web\helpers\CHtml.php(1654): CHtml::activeInputField('date', Object(Tasks), 'deadline1', Array)
#4 Z:\home\yii\www\framework\web\widgets\CActiveForm.php(680): CHtml::activeDateField(Object(Tasks), 'deadline1', '')
#5 Z:\home\yii\www\protected\views\tasks\index.php(120): CActiveForm->dateField(Object(Tasks), 'deadline1', '')
#6 Z:\home\yii\www\framework\web\CBaseController.php(126): require('Z:\home\yii\www...')
#7 Z:\home\yii\www\framework\web\CBaseController.php(95): CBaseController->renderInternal('Z:\home\yii\www...', Array, true)
#8 Z:\home\yii\www\framework\web\CController.php(869): CBaseController->renderFile('Z:\home\yii\www...', Array, true)
#9 Z:\home\yii\www\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#10 Z:\home\yii\www\protected\controllers\TasksController.php(110): CController->render('index', Array)
#11 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionIndex()
#12 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#13 Z:\home\yii\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#14 Z:\home\yii\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('')
#16 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('tasks')
#17 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#18 Z:\home\yii\www\index.php(13): CApplication->run()
#19 {main}
REQUEST_URI=/index.php/tasks/
---
2016/05/02 15:03:57 [error] [exception.CException] exception 'CException' with message 'Не определено свойство "Tasks.".' in Z:\home\yii\www\framework\base\CComponent.php:130
Stack trace:
#0 Z:\home\yii\www\framework\db\ar\CActiveRecord.php(145): CComponent->__get('')
#1 Z:\home\yii\www\framework\web\helpers\CHtml.php(2729): CActiveRecord->__get('')
#2 Z:\home\yii\www\framework\web\helpers\CHtml.php(2452): CHtml::resolveValue(Object(Tasks), '')
#3 Z:\home\yii\www\framework\web\helpers\CHtml.php(1654): CHtml::activeInputField('date', Object(Tasks), '', Array)
#4 Z:\home\yii\www\framework\web\widgets\CActiveForm.php(680): CHtml::activeDateField(Object(Tasks), '', '')
#5 Z:\home\yii\www\protected\views\tasks\index.php(120): CActiveForm->dateField(Object(Tasks), '', '')
#6 Z:\home\yii\www\framework\web\CBaseController.php(126): require('Z:\home\yii\www...')
#7 Z:\home\yii\www\framework\web\CBaseController.php(95): CBaseController->renderInternal('Z:\home\yii\www...', Array, true)
#8 Z:\home\yii\www\framework\web\CController.php(869): CBaseController->renderFile('Z:\home\yii\www...', Array, true)
#9 Z:\home\yii\www\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#10 Z:\home\yii\www\protected\controllers\TasksController.php(110): CController->render('index', Array)
#11 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionIndex()
#12 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#13 Z:\home\yii\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#14 Z:\home\yii\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('')
#16 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('tasks')
#17 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#18 Z:\home\yii\www\index.php(13): CApplication->run()
#19 {main}
REQUEST_URI=/index.php/tasks/
---
2016/05/02 15:04:11 [error] [php] Missing argument 2 for CActiveForm::dateField(), called in Z:\home\yii\www\protected\views\tasks\index.php on line 120 and defined (Z:\home\yii\www\framework\web\widgets\CActiveForm.php:678)
Stack trace:
#0 Z:\home\yii\www\framework\web\CBaseController.php(95): TasksController->renderInternal()
#1 Z:\home\yii\www\framework\web\CController.php(869): TasksController->renderFile()
#2 Z:\home\yii\www\framework\web\CController.php(782): TasksController->renderPartial()
#3 Z:\home\yii\www\protected\controllers\TasksController.php(110): TasksController->render()
#4 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionIndex()
#5 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#6 Z:\home\yii\www\framework\web\CController.php(286): TasksController->runAction()
#7 Z:\home\yii\www\framework\web\CController.php(265): TasksController->runActionWithFilters()
#8 Z:\home\yii\www\framework\web\CWebApplication.php(282): TasksController->run()
#9 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#10 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#11 Z:\home\yii\www\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php/tasks/
in Z:\home\yii\www\protected\views\tasks\index.php (120)
in Z:\home\yii\www\protected\controllers\TasksController.php (110)
in Z:\home\yii\www\index.php (13)
2016/05/02 15:08:35 [error] [exception.CException] exception 'CException' with message 'Не определено свойство "Tasks.".' in Z:\home\yii\www\framework\base\CComponent.php:130
Stack trace:
#0 Z:\home\yii\www\framework\db\ar\CActiveRecord.php(145): CComponent->__get('')
#1 Z:\home\yii\www\framework\web\helpers\CHtml.php(2729): CActiveRecord->__get('')
#2 Z:\home\yii\www\framework\web\helpers\CHtml.php(2452): CHtml::resolveValue(Object(Tasks), '')
#3 Z:\home\yii\www\framework\web\helpers\CHtml.php(1654): CHtml::activeInputField('date', Object(Tasks), '', Array)
#4 Z:\home\yii\www\framework\web\widgets\CActiveForm.php(680): CHtml::activeDateField(Object(Tasks), '', Array)
#5 Z:\home\yii\www\protected\views\tasks\index.php(120): CActiveForm->dateField(Object(Tasks), '')
#6 Z:\home\yii\www\framework\web\CBaseController.php(126): require('Z:\home\yii\www...')
#7 Z:\home\yii\www\framework\web\CBaseController.php(95): CBaseController->renderInternal('Z:\home\yii\www...', Array, true)
#8 Z:\home\yii\www\framework\web\CController.php(869): CBaseController->renderFile('Z:\home\yii\www...', Array, true)
#9 Z:\home\yii\www\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#10 Z:\home\yii\www\protected\controllers\TasksController.php(110): CController->render('index', Array)
#11 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionIndex()
#12 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#13 Z:\home\yii\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#14 Z:\home\yii\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('')
#16 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('tasks')
#17 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#18 Z:\home\yii\www\index.php(13): CApplication->run()
#19 {main}
REQUEST_URI=/index.php/tasks/
---
2016/05/02 15:45:50 [error] [exception.CException] exception 'CException' with message 'Не определено свойство "Tasks.deadline".' in Z:\home\yii\www\framework\base\CComponent.php:130
Stack trace:
#0 Z:\home\yii\www\framework\db\ar\CActiveRecord.php(145): CComponent->__get('deadline')
#1 Z:\home\yii\www\protected\views\tasks\index.php(22): CActiveRecord->__get('deadline')
#2 Z:\home\yii\www\framework\web\CBaseController.php(126): require('Z:\home\yii\www...')
#3 Z:\home\yii\www\framework\web\CBaseController.php(95): CBaseController->renderInternal('Z:\home\yii\www...', Array, true)
#4 Z:\home\yii\www\framework\web\CController.php(869): CBaseController->renderFile('Z:\home\yii\www...', Array, true)
#5 Z:\home\yii\www\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#6 Z:\home\yii\www\protected\controllers\TasksController.php(110): CController->render('index', Array)
#7 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionIndex()
#8 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 Z:\home\yii\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 Z:\home\yii\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('')
#12 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('tasks')
#13 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#14 Z:\home\yii\www\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/index.php/tasks/
---
2016/05/02 15:47:21 [error] [exception.CException] exception 'CException' with message 'Не определено свойство "Tasks.deadline".' in Z:\home\yii\www\framework\base\CComponent.php:130
Stack trace:
#0 Z:\home\yii\www\framework\db\ar\CActiveRecord.php(145): CComponent->__get('deadline')
#1 Z:\home\yii\www\protected\views\tasks\index.php(22): CActiveRecord->__get('deadline')
#2 Z:\home\yii\www\framework\web\CBaseController.php(126): require('Z:\home\yii\www...')
#3 Z:\home\yii\www\framework\web\CBaseController.php(95): CBaseController->renderInternal('Z:\home\yii\www...', Array, true)
#4 Z:\home\yii\www\framework\web\CController.php(869): CBaseController->renderFile('Z:\home\yii\www...', Array, true)
#5 Z:\home\yii\www\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#6 Z:\home\yii\www\protected\controllers\TasksController.php(110): CController->render('index', Array)
#7 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionIndex()
#8 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 Z:\home\yii\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 Z:\home\yii\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('')
#12 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('tasks')
#13 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#14 Z:\home\yii\www\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/index.php/tasks/
---
2016/05/02 16:59:13 [error] [exception.CException] exception 'CException' with message 'Не определено свойство "Tasks.deadline".' in Z:\home\yii\www\framework\base\CComponent.php:130
Stack trace:
#0 Z:\home\yii\www\framework\db\ar\CActiveRecord.php(145): CComponent->__get('deadline')
#1 Z:\home\yii\www\protected\views\tasks\task.php(12): CActiveRecord->__get('deadline')
#2 Z:\home\yii\www\framework\web\CBaseController.php(126): require('Z:\home\yii\www...')
#3 Z:\home\yii\www\framework\web\CBaseController.php(95): CBaseController->renderInternal('Z:\home\yii\www...', Array, true)
#4 Z:\home\yii\www\framework\web\CController.php(869): CBaseController->renderFile('Z:\home\yii\www...', Array, true)
#5 Z:\home\yii\www\framework\web\CController.php(782): CController->renderPartial('task', Array, true)
#6 Z:\home\yii\www\protected\controllers\TasksController.php(190): CController->render('task', Array)
#7 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionTask()
#8 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 Z:\home\yii\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 Z:\home\yii\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('task')
#12 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('tasks/task')
#13 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#14 Z:\home\yii\www\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/index.php/tasks/task?num=27
HTTP_REFERER=http://www.yii/index.php/tasks/
---
2016/05/02 18:30:40 [error] [exception.CException] exception 'CException' with message 'Не определено свойство "Tasks.deadline".' in Z:\home\yii\www\framework\base\CComponent.php:130
Stack trace:
#0 Z:\home\yii\www\framework\db\ar\CActiveRecord.php(145): CComponent->__get('deadline')
#1 Z:\home\yii\www\protected\views\tasks\task.php(12): CActiveRecord->__get('deadline')
#2 Z:\home\yii\www\framework\web\CBaseController.php(126): require('Z:\home\yii\www...')
#3 Z:\home\yii\www\framework\web\CBaseController.php(95): CBaseController->renderInternal('Z:\home\yii\www...', Array, true)
#4 Z:\home\yii\www\framework\web\CController.php(869): CBaseController->renderFile('Z:\home\yii\www...', Array, true)
#5 Z:\home\yii\www\framework\web\CController.php(782): CController->renderPartial('task', Array, true)
#6 Z:\home\yii\www\protected\controllers\TasksController.php(190): CController->render('task', Array)
#7 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionTask()
#8 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 Z:\home\yii\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 Z:\home\yii\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('task')
#12 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('tasks/task')
#13 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#14 Z:\home\yii\www\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/index.php/tasks/task?num=1
HTTP_REFERER=http://www.yii/index.php/tasks/
---
2016/05/02 19:29:06 [error] [php] include(CHTML.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (Z:\home\yii\www\framework\YiiBase.php:432)
Stack trace:
#0 Z:\home\yii\www\protected\views\tasks\task.php(12): spl_autoload_call()
#1 Z:\home\yii\www\framework\web\CBaseController.php(126): require()
#2 Z:\home\yii\www\framework\web\CBaseController.php(95): TasksController->renderInternal()
#3 Z:\home\yii\www\framework\web\CController.php(869): TasksController->renderFile()
#4 Z:\home\yii\www\framework\web\CController.php(782): TasksController->renderPartial()
#5 Z:\home\yii\www\protected\controllers\TasksController.php(143): TasksController->render()
#6 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionTask()
#7 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#8 Z:\home\yii\www\framework\web\CController.php(286): TasksController->runAction()
#9 Z:\home\yii\www\framework\web\CController.php(265): TasksController->runActionWithFilters()
#10 Z:\home\yii\www\framework\web\CWebApplication.php(282): TasksController->run()
#11 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#13 Z:\home\yii\www\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php/tasks/task?num=15
in Z:\home\yii\www\protected\views\tasks\task.php (12)
in Z:\home\yii\www\protected\controllers\TasksController.php (143)
in Z:\home\yii\www\index.php (13)
2016/05/02 19:30:57 [error] [php] include(CHTML.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (Z:\home\yii\www\framework\YiiBase.php:432)
Stack trace:
#0 Z:\home\yii\www\protected\views\tasks\task.php(12): spl_autoload_call()
#1 Z:\home\yii\www\framework\web\CBaseController.php(126): require()
#2 Z:\home\yii\www\framework\web\CBaseController.php(95): TasksController->renderInternal()
#3 Z:\home\yii\www\framework\web\CController.php(869): TasksController->renderFile()
#4 Z:\home\yii\www\framework\web\CController.php(782): TasksController->renderPartial()
#5 Z:\home\yii\www\protected\controllers\TasksController.php(143): TasksController->render()
#6 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionTask()
#7 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#8 Z:\home\yii\www\framework\web\CController.php(286): TasksController->runAction()
#9 Z:\home\yii\www\framework\web\CController.php(265): TasksController->runActionWithFilters()
#10 Z:\home\yii\www\framework\web\CWebApplication.php(282): TasksController->run()
#11 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#13 Z:\home\yii\www\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php/tasks/task?num=15
in Z:\home\yii\www\protected\views\tasks\task.php (12)
in Z:\home\yii\www\protected\controllers\TasksController.php (143)
in Z:\home\yii\www\index.php (13)
2016/05/02 19:31:13 [error] [php] include(CHTML.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (Z:\home\yii\www\framework\YiiBase.php:432)
Stack trace:
#0 Z:\home\yii\www\protected\views\tasks\task.php(12): spl_autoload_call()
#1 Z:\home\yii\www\framework\web\CBaseController.php(126): require()
#2 Z:\home\yii\www\framework\web\CBaseController.php(95): TasksController->renderInternal()
#3 Z:\home\yii\www\framework\web\CController.php(869): TasksController->renderFile()
#4 Z:\home\yii\www\framework\web\CController.php(782): TasksController->renderPartial()
#5 Z:\home\yii\www\protected\controllers\TasksController.php(143): TasksController->render()
#6 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionTask()
#7 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#8 Z:\home\yii\www\framework\web\CController.php(286): TasksController->runAction()
#9 Z:\home\yii\www\framework\web\CController.php(265): TasksController->runActionWithFilters()
#10 Z:\home\yii\www\framework\web\CWebApplication.php(282): TasksController->run()
#11 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#13 Z:\home\yii\www\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php/tasks/task?num=15
in Z:\home\yii\www\protected\views\tasks\task.php (12)
in Z:\home\yii\www\protected\controllers\TasksController.php (143)
in Z:\home\yii\www\index.php (13)
2016/05/02 19:31:52 [error] [php] include(CHTML.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (Z:\home\yii\www\framework\YiiBase.php:432)
Stack trace:
#0 Z:\home\yii\www\protected\views\tasks\task.php(12): spl_autoload_call()
#1 Z:\home\yii\www\framework\web\CBaseController.php(126): require()
#2 Z:\home\yii\www\framework\web\CBaseController.php(95): TasksController->renderInternal()
#3 Z:\home\yii\www\framework\web\CController.php(869): TasksController->renderFile()
#4 Z:\home\yii\www\framework\web\CController.php(782): TasksController->renderPartial()
#5 Z:\home\yii\www\protected\controllers\TasksController.php(143): TasksController->render()
#6 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionTask()
#7 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#8 Z:\home\yii\www\framework\web\CController.php(286): TasksController->runAction()
#9 Z:\home\yii\www\framework\web\CController.php(265): TasksController->runActionWithFilters()
#10 Z:\home\yii\www\framework\web\CWebApplication.php(282): TasksController->run()
#11 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#13 Z:\home\yii\www\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php/tasks/task?num=15
in Z:\home\yii\www\protected\views\tasks\task.php (12)
in Z:\home\yii\www\protected\controllers\TasksController.php (143)
in Z:\home\yii\www\index.php (13)
2016/05/02 19:31:54 [error] [php] include(CHTML.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (Z:\home\yii\www\framework\YiiBase.php:432)
Stack trace:
#0 Z:\home\yii\www\protected\views\tasks\task.php(12): spl_autoload_call()
#1 Z:\home\yii\www\framework\web\CBaseController.php(126): require()
#2 Z:\home\yii\www\framework\web\CBaseController.php(95): TasksController->renderInternal()
#3 Z:\home\yii\www\framework\web\CController.php(869): TasksController->renderFile()
#4 Z:\home\yii\www\framework\web\CController.php(782): TasksController->renderPartial()
#5 Z:\home\yii\www\protected\controllers\TasksController.php(143): TasksController->render()
#6 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionTask()
#7 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#8 Z:\home\yii\www\framework\web\CController.php(286): TasksController->runAction()
#9 Z:\home\yii\www\framework\web\CController.php(265): TasksController->runActionWithFilters()
#10 Z:\home\yii\www\framework\web\CWebApplication.php(282): TasksController->run()
#11 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#13 Z:\home\yii\www\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php/tasks/task?num=15
in Z:\home\yii\www\protected\views\tasks\task.php (12)
in Z:\home\yii\www\protected\controllers\TasksController.php (143)
in Z:\home\yii\www\index.php (13)
2016/05/02 19:32:22 [error] [php] include(CHTML.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (Z:\home\yii\www\framework\YiiBase.php:432)
Stack trace:
#0 Z:\home\yii\www\protected\views\tasks\task.php(12): spl_autoload_call()
#1 Z:\home\yii\www\framework\web\CBaseController.php(126): require()
#2 Z:\home\yii\www\framework\web\CBaseController.php(95): TasksController->renderInternal()
#3 Z:\home\yii\www\framework\web\CController.php(869): TasksController->renderFile()
#4 Z:\home\yii\www\framework\web\CController.php(782): TasksController->renderPartial()
#5 Z:\home\yii\www\protected\controllers\TasksController.php(143): TasksController->render()
#6 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionTask()
#7 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#8 Z:\home\yii\www\framework\web\CController.php(286): TasksController->runAction()
#9 Z:\home\yii\www\framework\web\CController.php(265): TasksController->runActionWithFilters()
#10 Z:\home\yii\www\framework\web\CWebApplication.php(282): TasksController->run()
#11 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#13 Z:\home\yii\www\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php/tasks/task?num=15
in Z:\home\yii\www\protected\views\tasks\task.php (12)
in Z:\home\yii\www\protected\controllers\TasksController.php (143)
in Z:\home\yii\www\index.php (13)
2016/05/02 19:32:42 [error] [php] include(CHTML.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (Z:\home\yii\www\framework\YiiBase.php:432)
Stack trace:
#0 Z:\home\yii\www\protected\views\tasks\task.php(12): spl_autoload_call()
#1 Z:\home\yii\www\framework\web\CBaseController.php(126): require()
#2 Z:\home\yii\www\framework\web\CBaseController.php(95): TasksController->renderInternal()
#3 Z:\home\yii\www\framework\web\CController.php(869): TasksController->renderFile()
#4 Z:\home\yii\www\framework\web\CController.php(782): TasksController->renderPartial()
#5 Z:\home\yii\www\protected\controllers\TasksController.php(143): TasksController->render()
#6 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionTask()
#7 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#8 Z:\home\yii\www\framework\web\CController.php(286): TasksController->runAction()
#9 Z:\home\yii\www\framework\web\CController.php(265): TasksController->runActionWithFilters()
#10 Z:\home\yii\www\framework\web\CWebApplication.php(282): TasksController->run()
#11 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#13 Z:\home\yii\www\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php/tasks/task?num=15
in Z:\home\yii\www\protected\views\tasks\task.php (12)
in Z:\home\yii\www\protected\controllers\TasksController.php (143)
in Z:\home\yii\www\index.php (13)
2016/05/02 19:32:44 [error] [php] include(CHTML.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (Z:\home\yii\www\framework\YiiBase.php:432)
Stack trace:
#0 Z:\home\yii\www\protected\views\tasks\task.php(12): spl_autoload_call()
#1 Z:\home\yii\www\framework\web\CBaseController.php(126): require()
#2 Z:\home\yii\www\framework\web\CBaseController.php(95): TasksController->renderInternal()
#3 Z:\home\yii\www\framework\web\CController.php(869): TasksController->renderFile()
#4 Z:\home\yii\www\framework\web\CController.php(782): TasksController->renderPartial()
#5 Z:\home\yii\www\protected\controllers\TasksController.php(143): TasksController->render()
#6 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionTask()
#7 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#8 Z:\home\yii\www\framework\web\CController.php(286): TasksController->runAction()
#9 Z:\home\yii\www\framework\web\CController.php(265): TasksController->runActionWithFilters()
#10 Z:\home\yii\www\framework\web\CWebApplication.php(282): TasksController->run()
#11 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#13 Z:\home\yii\www\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php/tasks/task?num=15
in Z:\home\yii\www\protected\views\tasks\task.php (12)
in Z:\home\yii\www\protected\controllers\TasksController.php (143)
in Z:\home\yii\www\index.php (13)
2016/05/04 08:26:59 [error] [system.db.CDbCommand] Не удалось выполнить CDbCommand::fetchAll(): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'datepicker' in 'order clause'. Выполнявшийся SQL-запрос: SELECT * FROM tasks ORDER BY done DESC, datepicker ASC.
in Z:\home\yii\www\protected\controllers\TasksController.php (35)
in Z:\home\yii\www\index.php (13)
2016/05/04 08:26:59 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand не удалось исполнить SQL-запрос: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'datepicker' in 'order clause'. The SQL statement executed was: SELECT * FROM tasks ORDER BY done DESC, datepicker ASC' in Z:\home\yii\www\framework\db\CDbCommand.php:543
Stack trace:
#0 Z:\home\yii\www\framework\db\CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 Z:\home\yii\www\framework\db\ar\CActiveRecord.php(1586): CDbCommand->queryAll()
#2 Z:\home\yii\www\protected\controllers\TasksController.php(35): CActiveRecord->findAllBySql('SELECT * FROM t...')
#3 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionIndex()
#4 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 Z:\home\yii\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#6 Z:\home\yii\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('')
#8 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('tasks')
#9 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 Z:\home\yii\www\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/index.php/tasks/
---
2016/05/04 08:28:49 [error] [system.db.CDbCommand] Не удалось выполнить CDbCommand::fetchAll(): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'datepicker' in 'order clause'. Выполнявшийся SQL-запрос: SELECT * FROM tasks ORDER BY done DESC, datepicker ASC.
in Z:\home\yii\www\protected\controllers\TasksController.php (35)
in Z:\home\yii\www\index.php (13)
2016/05/04 08:28:49 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand не удалось исполнить SQL-запрос: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'datepicker' in 'order clause'. The SQL statement executed was: SELECT * FROM tasks ORDER BY done DESC, datepicker ASC' in Z:\home\yii\www\framework\db\CDbCommand.php:543
Stack trace:
#0 Z:\home\yii\www\framework\db\CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 Z:\home\yii\www\framework\db\ar\CActiveRecord.php(1586): CDbCommand->queryAll()
#2 Z:\home\yii\www\protected\controllers\TasksController.php(35): CActiveRecord->findAllBySql('SELECT * FROM t...')
#3 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionIndex()
#4 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 Z:\home\yii\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#6 Z:\home\yii\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('')
#8 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('tasks')
#9 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 Z:\home\yii\www\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/index.php/tasks/
---
2016/05/04 08:36:55 [error] [php] Cannot use a scalar value as an array (Z:\home\yii\www\framework\web\helpers\CHtml.php:425)
Stack trace:
#0 Z:\home\yii\www\framework\web\CBaseController.php(95): TasksController->renderInternal()
#1 Z:\home\yii\www\framework\web\CController.php(869): TasksController->renderFile()
#2 Z:\home\yii\www\framework\web\CController.php(782): TasksController->renderPartial()
#3 Z:\home\yii\www\protected\controllers\TasksController.php(85): TasksController->render()
#4 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionIndex()
#5 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#6 Z:\home\yii\www\framework\web\CController.php(286): TasksController->runAction()
#7 Z:\home\yii\www\framework\web\CController.php(265): TasksController->runActionWithFilters()
#8 Z:\home\yii\www\framework\web\CWebApplication.php(282): TasksController->run()
#9 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#10 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#11 Z:\home\yii\www\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php/tasks/
in Z:\home\yii\www\protected\views\tasks\index.php (23)
in Z:\home\yii\www\protected\controllers\TasksController.php (85)
in Z:\home\yii\www\index.php (13)
2016/05/04 09:26:15 [error] [system.db.CDbCommand] Не удалось выполнить CDbCommand::fetchAll(): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'yii.fio' doesn't exist. Выполнявшийся SQL-запрос: SHOW FULL COLUMNS FROM `fio`.
in Z:\home\yii\www\protected\controllers\TasksController.php (32)
in Z:\home\yii\www\index.php (13)
2016/05/04 09:26:16 [error] [exception.CDbException] exception 'CDbException' with message 'Таблица "fio", упомянутая в записи active record класса "Fio", не найдена в базе данных.' in Z:\home\yii\www\framework\db\ar\CActiveRecord.php:2387
Stack trace:
#0 Z:\home\yii\www\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Fio))
#1 Z:\home\yii\www\framework\db\ar\CActiveRecord.php(79): CActiveRecord->getMetaData()
#2 Z:\home\yii\www\protected\controllers\TasksController.php(32): CActiveRecord->__construct()
#3 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionIndex()
#4 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 Z:\home\yii\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#6 Z:\home\yii\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 Z:\home\yii\www\framework\web\CWebApplication.php(282): CController->run('')
#8 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController('tasks')
#9 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 Z:\home\yii\www\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/index.php/tasks
---
2016/05/04 09:27:19 [error] [php] include(Fio.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (Z:\home\yii\www\framework\YiiBase.php:432)
Stack trace:
#0 Z:\home\yii\www\protected\controllers\TasksController.php(32): spl_autoload_call()
#1 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionIndex()
#2 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 Z:\home\yii\www\framework\web\CController.php(286): TasksController->runAction()
#4 Z:\home\yii\www\framework\web\CController.php(265): TasksController->runActionWithFilters()
#5 Z:\home\yii\www\framework\web\CWebApplication.php(282): TasksController->run()
#6 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#7 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#8 Z:\home\yii\www\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php/tasks
in Z:\home\yii\www\protected\controllers\TasksController.php (32)
in Z:\home\yii\www\index.php (13)
2016/05/04 09:29:07 [error] [php] include(Fio.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (Z:\home\yii\www\framework\YiiBase.php:432)
Stack trace:
#0 Z:\home\yii\www\protected\controllers\TasksController.php(32): spl_autoload_call()
#1 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionIndex()
#2 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 Z:\home\yii\www\framework\web\CController.php(286): TasksController->runAction()
#4 Z:\home\yii\www\framework\web\CController.php(265): TasksController->runActionWithFilters()
#5 Z:\home\yii\www\framework\web\CWebApplication.php(282): TasksController->run()
#6 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#7 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#8 Z:\home\yii\www\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php/tasks
in Z:\home\yii\www\protected\controllers\TasksController.php (32)
in Z:\home\yii\www\index.php (13)
2016/05/04 09:30:41 [error] [php] include(Fio.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (Z:\home\yii\www\framework\YiiBase.php:432)
Stack trace:
#0 Z:\home\yii\www\protected\controllers\TasksController.php(32): spl_autoload_call()
#1 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionIndex()
#2 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 Z:\home\yii\www\framework\web\CController.php(286): TasksController->runAction()
#4 Z:\home\yii\www\framework\web\CController.php(265): TasksController->runActionWithFilters()
#5 Z:\home\yii\www\framework\web\CWebApplication.php(282): TasksController->run()
#6 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#7 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#8 Z:\home\yii\www\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php/tasks
in Z:\home\yii\www\protected\controllers\TasksController.php (32)
in Z:\home\yii\www\index.php (13)
2016/05/04 09:30:42 [error] [php] include(Fio.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (Z:\home\yii\www\framework\YiiBase.php:432)
Stack trace:
#0 Z:\home\yii\www\protected\controllers\TasksController.php(32): spl_autoload_call()
#1 Z:\home\yii\www\framework\web\actions\CInlineAction.php(49): TasksController->actionIndex()
#2 Z:\home\yii\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 Z:\home\yii\www\framework\web\CController.php(286): TasksController->runAction()
#4 Z:\home\yii\www\framework\web\CController.php(265): TasksController->runActionWithFilters()
#5 Z:\home\yii\www\framework\web\CWebApplication.php(282): TasksController->run()
#6 Z:\home\yii\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#7 Z:\home\yii\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#8 Z:\home\yii\www\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php/tasks
in Z:\home\yii\www\protected\controllers\TasksController.php (32)
in Z:\home\yii\www\index.php (13)
